// Test generated by RoostGPT for test test using AI Type Open AI and AI Model gpt-4

package main

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestGetAllCandidates_414119e2ca(t *testing.T) {
	t.Run("returns All Candidates", func(t *testing.T) {
		request, _ := http.NewRequest(http.MethodGet, "/candidates", nil)
		response := httptest.NewRecorder()

		getAllCandidates(response, request)

		got := response.Body.String()
		want := "All Candidates"

		if got != want {
			t.Errorf("got %q, want %q", got, want)
		}
	})

	t.Run("returns status code 200", func(t *testing.T) {
		request, _ := http.NewRequest(http.MethodGet, "/candidates", nil)
		response := httptest.NewRecorder()

		getAllCandidates(response, request)

		got := response.Result().StatusCode
		want := http.StatusOK

		if got != want {
			t.Errorf("got %d, want %d", got, want)
		}
	})

	t.Run("returns status code 404 when route is not found", func(t *testing.T) {
		request, _ := http.NewRequest(http.MethodGet, "/not-a-route", nil)
		response := httptest.NewRecorder()

		getAllCandidates(response, request)

		got := response.Result().StatusCode
		want := http.StatusNotFound

		if got != want {
			t.Errorf("got %d, want %d", got, want)
		}
	})
}
